#include "hud.h"
#include "parsemsg.h"
#include "utils.h"

race_player_info_t g_RacePlayerInfo[MAX_PLAYERS+1];
static int state=-1,heat=1,heats=1,lap=0,laps=3,checkpoint=0,checkpoints=0,countdown=0,finishSeconds=0,elapsedMs=0,lastLapMs=0;
static float receivedAt=0,goUntil=0;

static void FormatRaceTime(char*out,size_t size,int ms){if(ms<=0){Q_strncpy(out,"--:--.---",size);return;}Q_snprintf(out,size,"%02d:%02d.%03d",ms/60000,(ms/1000)%60,ms%1000);}
void ReadRaceHudMessage(){int old=state;state=READ_BYTE();if(old==1&&state==2)goUntil=gHUD.m_flTime+1;heat=READ_BYTE();heats=READ_BYTE();lap=READ_BYTE();laps=READ_BYTE();checkpoint=READ_BYTE();checkpoints=READ_BYTE();countdown=READ_BYTE();finishSeconds=READ_SHORT();elapsedMs=READ_LONG();lastLapMs=READ_LONG();receivedAt=gHUD.m_flTime;}
void ReadRaceDataMessage(){int i=READ_BYTE();if(i<=0||i>MAX_PLAYERS)return;race_player_info_t&r=g_RacePlayerInfo[i];r.place=READ_BYTE();r.laps=READ_BYTE();r.status=READ_BYTE();r.timeMs=READ_LONG();r.averageMs=READ_LONG();r.points=READ_SHORT();r.wins=READ_BYTE();r.podiums=READ_BYTE();r.heats=READ_BYTE();r.dnfs=READ_BYTE();}
static void DrawCenter(const char*s,int y,int r,int g,int b){gHUD.DrawHudString((ScreenWidth-ConsoleStringLen(s))/2,y,ScreenWidth,s,r,g,b);}
int DrawRaceHud(float time){if(state<0)return 1;if(state==4)return DrawRaceScoreboard(time);char text[128],clock[24];if(state==0){Q_snprintf(text,sizeof(text),"%s - Heat %d/%d",gHUD.m_Car.IsVisible()?"READY":"ENTER A CAR",heat,heats);DrawCenter(text,40,255,190,30);return 1;}if(state==1){if(countdown)Q_snprintf(text,sizeof(text),"%d",countdown);else Q_strncpy(text,"GO!",sizeof(text));DrawCenter(text,(int)(ScreenHeight*.32f),255,190,30);return 1;}if(time<goUntil)DrawCenter("GO!",(int)(ScreenHeight*.32f),80,255,80);int shown=elapsedMs+((state==2||state==3)?(int)((time-receivedAt)*1000):0);FormatRaceTime(clock,sizeof(clock),shown);Q_snprintf(text,sizeof(text),"Heat %d/%d  Laps %d/%d  Checkpoint %d/%d  %s",heat,heats,Q_min(lap,laps),laps,checkpoint,checkpoints,clock);DrawCenter(text,30,255,190,30);if(lastLapMs){FormatRaceTime(clock,sizeof(clock),lastLapMs);Q_snprintf(text,sizeof(text),"Last lap: %s",clock);DrawCenter(text,30+gHUD.m_iFontHeight+3,230,230,230);}if(state==3){Q_snprintf(text,sizeof(text),"Finish closes in %d",finishSeconds);DrawCenter(text,30+(gHUD.m_iFontHeight+3)*2,255,80,60);}return 1;}
int DrawRaceScoreboard(float){gHUD.m_Scoreboard.GetAllPlayersInfo();const int width=620,x=(ScreenWidth-width)/2;int y=60,line=Q_max(14,gHUD.m_iFontHeight+3);const bool overall=state==4&&heat>=heats;DrawCenter(overall?"RACE CHAMPIONSHIP":"RACE RESULTS",y,255,190,30);y+=line*2;gHUD.DrawHudString(x,y,ScreenWidth,overall?"#   Player                         Points  Wins  Podiums  Heats  DNF":"#   Player                    Laps     Average       Time       Status",255,190,30);y+=line;bool drawn[MAX_PLAYERS+1]={};for(int row=0;row<MAX_PLAYERS;row++){int best=0;for(int i=1;i<MAX_PLAYERS;i++){if(drawn[i]||!g_PlayerInfoList[i].name)continue;if(!best)best=i;else{race_player_info_t&a=g_RacePlayerInfo[i],&b=g_RacePlayerInfo[best];if(overall?a.points>b.points:(a.place>0&&(b.place==0||a.place<b.place)))best=i;}}if(!best)break;drawn[best]=true;race_player_info_t&r=g_RacePlayerInfo[best];char out[192],avg[24],total[24],place[8];FormatRaceTime(avg,sizeof(avg),r.averageMs);FormatRaceTime(total,sizeof(total),r.timeMs);if(r.place)Q_snprintf(place,sizeof(place),"%d",r.place);else Q_strncpy(place,"-",sizeof(place));if(overall)Q_snprintf(out,sizeof(out),"%-3d %-30s %6d %5d %8d %6d %4d",row+1,g_PlayerInfoList[best].name,r.points,r.wins,r.podiums,r.heats,r.dnfs);else Q_snprintf(out,sizeof(out),"%-3s %-25s %2d/%-2d   %s   %s   %s",place,g_PlayerInfoList[best].name,r.laps,laps,avg,total,r.status==1?"FINISHED":(r.status==2?"DNF":"RACING"));gHUD.DrawHudString(x,y,ScreenWidth,out,255,255,255);y+=line;}return 1;}
