#include "weapon_surveillance_camera.h"
#include "server_weapon_layer_impl.h"
#include "weapons/surveillance_camera.h"
#include "weapons/tripmine.h"
#include "player.h"
#include "user_messages.h"
class CSurveillanceCameraEntity:public CBaseAnimating{DECLARE_CLASS(CSurveillanceCameraEntity,CBaseAnimating);public:void Spawn()override{pev->movetype=MOVETYPE_NONE;pev->solid=SOLID_BBOX;pev->takedamage=DAMAGE_YES;pev->health=10.0f;SET_MODEL(edict(),"models/weapon/Camera/w_camera.mdl");pev->frame=0;pev->framerate=0;ResetSequenceInfo();UTIL_SetSize(pev,Vector(-8,-8,-8),Vector(8,8,8));SetBits(pev->effects,EF_NOINTERP|EF_MERGE_VISIBILITY);}void Killed(entvars_t*pevAttacker,int iGib)override{UTIL_Sparks(GetAbsOrigin());EMIT_SOUND(edict(),CHAN_BODY,"buttons/spark5.wav",1.0f,ATTN_NORM);CBasePlayer*owner=pev->euser1?static_cast<CBasePlayer*>(CBaseEntity::Instance(pev->euser1)):nullptr;if(owner&&owner->m_pActiveItem&&owner->m_pActiveItem->iWeaponID()==WEAPON_SURVEILLANCE_CAMERA)static_cast<CSurveillanceCamera*>(owner->m_pActiveItem)->OnCameraDestroyed(this);CBaseEntity*view=CBaseEntity::Instance(pev->euser2);if(view)UTIL_Remove(view);UTIL_Remove(this);}};
class CSurveillanceCameraView:public CBaseEntity{DECLARE_CLASS(CSurveillanceCameraView,CBaseEntity);public:void Spawn()override{pev->movetype=MOVETYPE_NONE;pev->solid=SOLID_NOT;SET_MODEL(edict(),"models/weapon/Camera/w_camera.mdl");SetBits(pev->effects,EF_NODRAW|EF_MERGE_VISIBILITY|EF_NOINTERP);}};
LINK_ENTITY_TO_CLASS(weapon_camera,CSurveillanceCamera);LINK_ENTITY_TO_CLASS(surveillance_camera,CSurveillanceCameraEntity);LINK_ENTITY_TO_CLASS(surveillance_camera_view,CSurveillanceCameraView);
CSurveillanceCamera::CSurveillanceCamera(){auto layer=std::make_unique<CServerWeaponLayerImpl>(this);m_pWeaponContext=std::make_unique<CSurveillanceCameraWeaponContext>(std::move(layer));}
void CSurveillanceCamera::Spawn(){Precache();SET_MODEL(edict(),"models/weapon/Camera/w_camera.mdl");FallInit();}
void CSurveillanceCamera::Precache(){PRECACHE_MODEL("models/weapon/Camera/v_camera.mdl");PRECACHE_MODEL("models/weapon/Camera/v_tablet.mdl");PRECACHE_MODEL("models/weapon/Camera/w_camera.mdl");PRECACHE_MODEL("models/p_satchel_radio.mdl");PRECACHE_SOUND("weapons/mine_deploy.wav");PRECACHE_SOUND("buttons/spark5.wav");UTIL_PrecacheOther("surveillance_camera");UTIL_PrecacheOther("surveillance_camera_view");}
int CSurveillanceCamera::AddToPlayer(CBasePlayer*player){ItemInfo info={};if(GetItemInfo(&info)&&info.iId>0&&info.iId<MAX_WEAPONS)CBaseWeaponContext::ItemInfoArray[info.iId]=info;if(!CBasePlayerWeapon::AddToPlayer(player))return FALSE;MESSAGE_BEGIN(MSG_ONE,gmsgWeaponList,NULL,player->pev);WRITE_STRING(info.pszName);WRITE_BYTE(player->GetAmmoIndex(info.pszAmmo1));WRITE_BYTE(info.iMaxAmmo1);WRITE_BYTE(player->GetAmmoIndex(info.pszAmmo2));WRITE_BYTE(info.iMaxAmmo2);WRITE_BYTE(info.iSlot);WRITE_BYTE(info.iPosition);WRITE_BYTE(info.iId);WRITE_BYTE(info.iFlags);MESSAGE_END();MESSAGE_BEGIN(MSG_ONE,gmsgWeapons,NULL,player->pev);for(int byteIndex=0;byteIndex<MAX_WEAPON_BYTES;++byteIndex){byte owned=0;for(int bit=0;bit<8;++bit){int weaponId=byteIndex*8+bit;if(weaponId<MAX_WEAPONS&&player->HasWeapon(weaponId))owned|=1<<bit;}WRITE_BYTE(owned);}MESSAGE_END();int ammo=m_pWeaponContext->PrimaryAmmoIndex();if(ammo>=0&&player->m_rgAmmo[ammo]<1)player->m_rgAmmo[ammo]=1;return TRUE;}
int CSurveillanceCamera::AddDuplicate(CBasePlayerItem*original){auto*owned=static_cast<CSurveillanceCamera*>(original);int ammo=owned->m_pWeaponContext->PrimaryAmmoIndex();if(ammo>=0&&owned->m_pPlayer->m_rgAmmo[ammo]<1){owned->m_pPlayer->m_rgAmmo[ammo]=1;return TRUE;}return FALSE;}
CSurveillanceCameraEntity*CSurveillanceCamera::FindCamera(int ordinal,int*count)const{int found=0;CBaseEntity*e=nullptr;CSurveillanceCameraEntity*r=nullptr;while((e=UTIL_FindEntityByClassname(e,"surveillance_camera"))!=nullptr)if(e->pev->euser1==(m_pPlayer?m_pPlayer->edict():nullptr)){++found;if(e->pev->iuser3==ordinal+1)r=static_cast<CSurveillanceCameraEntity*>(e);}if(count)*count=found;return r;}
bool CSurveillanceCamera::HasCameras()const{int count=0;FindCamera(-1,&count);return count>0;}
bool CSurveillanceCamera::PlaceCamera(){int count=0;FindCamera(-1,&count);if(count>=3){ClientPrint(m_pPlayer->pev,HUD_PRINTCENTER,"Camera limit reached");return false;}int cameraIndex=0;while(cameraIndex<3&&FindCamera(cameraIndex))++cameraIndex;if(cameraIndex>=3)return false;UTIL_MakeVectors(m_pPlayer->pev->v_angle+m_pPlayer->pev->punchangle);TraceResult tr;Vector start=m_pPlayer->GetGunPosition();UTIL_TraceLine(start,start+gpGlobals->v_forward*128.0f,ignore_monsters,m_pPlayer->edict(),&tr);CBaseEntity*surface=tr.flFraction<1.0f?CBaseEntity::Instance(tr.pHit):nullptr;if(!surface||!(surface->IsBSPModel()||surface->IsCustomModel())||FBitSet(surface->pev->flags,FL_CONVEYOR))return false;Vector angles=UTIL_VecToAngles(tr.vecPlaneNormal);angles.z=0;Vector mineOrigin=tr.vecEndPos;auto*camera=static_cast<CSurveillanceCameraEntity*>(CBaseEntity::Create("surveillance_camera",mineOrigin,angles,m_pPlayer->edict()));if(!camera)return false;auto*view=CBaseEntity::Create("surveillance_camera_view",tr.vecEndPos+tr.vecPlaneNormal*14.0f,angles,m_pPlayer->edict());if(!view){UTIL_Remove(camera);return false;}camera->pev->euser1=m_pPlayer->edict();camera->pev->euser2=view->edict();camera->pev->iuser1=m_pPlayer->entindex();camera->pev->iuser2=view->entindex();camera->pev->iuser3=cameraIndex+1;camera->pev->iuser4=0x5346434D;camera->pev->vuser1=angles;view->pev->euser1=camera->edict();view->pev->iuser4=0x5346434D;if(surface!=g_pWorld){camera->SetParent(surface);view->SetParent(surface);}EMIT_SOUND(camera->edict(),CHAN_BODY,"weapons/mine_deploy.wav",1.0f,ATTN_NORM);m_iSelectedCamera=cameraIndex;m_bViewingCamera=FALSE;return true;}
void CSurveillanceCamera::ToggleCameraView(){if(m_bViewingCamera){LeaveCameraView();return;}auto*camera=FindCamera(m_iSelectedCamera);if(!camera){for(int i=0;i<3&&!camera;++i)if((camera=FindCamera(i))!=nullptr)m_iSelectedCamera=i;}if(!camera)return;CBaseEntity*view=CBaseEntity::Instance(camera->pev->euser2);if(!view)return;m_bViewingCamera=TRUE;m_bCameraZoom=FALSE;m_pPlayer->pev->fov=m_pPlayer->m_iFOV=0;m_vecViewStartAngles=camera->pev->vuser1;Vector viewAngles=view->GetAbsAngles();m_pPlayer->pev->v_angle=viewAngles;m_pPlayer->pev->angles=viewAngles;m_pPlayer->pev->fixangle=TRUE;SET_VIEW(m_pPlayer->edict(),view->edict());m_flNextCameraLabel=0;}
void CSurveillanceCamera::LeaveCameraView(){if(!m_pPlayer||!m_bViewingCamera)return;m_bViewingCamera=FALSE;m_bCameraZoom=FALSE;m_pPlayer->pev->fov=m_pPlayer->m_iFOV=0;SET_VIEW(m_pPlayer->edict(),m_pPlayer->edict());ClientPrint(m_pPlayer->pev,HUD_PRINTCENTER,"");}
void CSurveillanceCamera::ToggleCameraZoom(){if(!m_pPlayer||!m_bViewingCamera)return;m_bCameraZoom=!m_bCameraZoom;m_pPlayer->pev->fov=m_pPlayer->m_iFOV=m_bCameraZoom?22:0;}
void CSurveillanceCamera::SelectNextCamera(){int next=-1;for(int offset=1;offset<=3;++offset){int candidate=(m_iSelectedCamera+offset)%3;if(FindCamera(candidate)){next=candidate;break;}}if(next<0)return;m_iSelectedCamera=next;if(m_bViewingCamera){m_bViewingCamera=FALSE;ToggleCameraView();}}
void CSurveillanceCamera::UpdateCameraView(){if(!m_bViewingCamera||!m_pPlayer)return;auto*camera=FindCamera(m_iSelectedCamera);CBaseEntity*view=camera?CBaseEntity::Instance(camera->pev->euser2):nullptr;if(!camera||!view){LeaveCameraView();return;}if(gpGlobals->time>=m_flNextCameraLabel){ClientPrint(m_pPlayer->pev,HUD_PRINTCENTER,UTIL_VarArgs("Camera %02d",m_iSelectedCamera+1));m_flNextCameraLabel=gpGlobals->time+1.0f;}Vector delta=m_pPlayer->pev->v_angle-m_vecViewStartAngles;bool clamped=false;for(int i=0;i<2;i++){while(delta[i]>180)delta[i]-=360;while(delta[i]<-180)delta[i]+=360;float limited=Q_max(-25.0f,Q_min(25.0f,delta[i]));clamped|=limited!=delta[i];delta[i]=limited;}Vector viewAngles=m_vecViewStartAngles+Vector(delta.x,delta.y,0);view->SetAbsAngles(viewAngles);if(clamped){m_pPlayer->pev->v_angle=viewAngles;m_pPlayer->pev->angles=viewAngles;m_pPlayer->pev->fixangle=TRUE;}}
void CSurveillanceCamera::UpdateViewModels(){if(!m_pPlayer)return;m_pPlayer->pev->viewmodel=MAKE_STRING("models/weapon/Camera/v_tablet.mdl");m_pPlayer->pev->iuser3=m_pPlayer->m_rgAmmo[m_pWeaponContext->PrimaryAmmoIndex()]>0?MODEL_INDEX("models/weapon/Camera/v_camera.mdl"):0;}
void CSurveillanceCamera::ClearViewModels(){if(m_pPlayer)m_pPlayer->pev->iuser3=0;}
void CSurveillanceCamera::OnCameraDestroyed(CSurveillanceCameraEntity*camera){const int removedIndex=camera->pev->iuser3-1;if(m_bViewingCamera&&m_iSelectedCamera==removedIndex)LeaveCameraView();if(m_iSelectedCamera==removedIndex){for(int offset=1;offset<=3;++offset){int candidate=(removedIndex+offset)%3;CSurveillanceCameraEntity*remaining=FindCamera(candidate);if(remaining&&remaining!=camera){m_iSelectedCamera=candidate;return;}}m_iSelectedCamera=0;}}
